### ISSUE TITLE
Constantly getting stuck in blocks

### ISSUE THREAD

**Issue by vichvich4444** [xtreme8000/aof-opengl#102]
Especially in tunnels and other close spaces. Sometimes if you jump in the 1 block-wide tunnel the jump-sound glitches.

**Comment by xtreme8000** [comment]
which version are you on?

**Comment by vichvich4444** [comment]
On the last - v0.1.4-beta

**Comment by xtreme8000** [comment]
This was fixed in 9dc9e9722469add3a1bb2d155578c8fcd4e907da about 7 months ago.
You really should use one of the [nightly builds](http://bytebit.info.tm/jenkins/job/BetterSpades/) since v0.1.4 is very outdated.

(if you can't update rn the issue can also be resolved by enabling v-sync in settings)

**Comment by vichvich4444** [comment]
Issue solved by using v-sync as you said.
