### ISSUE TITLE
CMake can't find any external libs

### ISSUE THREAD

**Issue by LEFTazs** [xtreme8000/aof-opengl#107]
I followed the wiki (https://github.com/xtreme8000/BetterSpades/wiki/Building-for-Windows) to build the source code on windows.
Unfortunately cmake fails with "Could NOT find GLEW (missing: GLEW_LIBRARIES)".
In fact, if I comment it out in the cmake file, all the other libraries will be missing too, even though I set them up with the help of the wiki.

What am I doing wrong? Is the wiki outdated?

**Comment by xtreme8000** [comment]
Thanks I quickly updated the wiki. All dependencies must have a `lib<name>.a` file that should be placed in `deps/`.

**Comment by LEFTazs** [comment]
Alright, thank you
