### ISSUE TITLE
Cannot play on Wayland

### ISSUE THREAD

**Issue by ghost** [xtreme8000/aof-opengl#109]
Running Arch Linux, installed glew-wayland and glfw-wayland, compiled BetterSpades and client's window is not responding, the log is:
```
00:23:08 INFO   main.c:629: Game started!
00:23:09 FATAL main.c:583: Major error occured: [65544] Wayland: Focusing a window requires user interaction
```

**Comment by xtreme8000** [comment]
This is a issue with GLFW3, not BetterSpades.

**Comment by ghost** [comment]
Ok, sorry for noise.
