### ISSUE TITLE
You gotta add hold to aim down sights

### ISSUE THREAD

**Issue by morytain** [xtreme8000/aof-opengl#112]
please

**Comment by morytain** [comment]
also, please add an fov slider up to 90 like openspades, it looks like im playing on console

**Comment by xtreme8000** [comment]
> also, please add an fov slider up to 90 like openspades, it looks like im playing on console

I will do testing on fov. Expect both features to be added.

**Comment by xtreme8000** [comment]
FOV added in https://github.com/xtreme8000/BetterSpades/commit/97585334ba5464d7cb3a7b2ae9af0cf1a8163ee2
