### ISSUE TITLE
Ugly voxlap models with high FOV

### ISSUE THREAD

**Issue by ghost** [xtreme8000/aof-opengl#113]
Increase the FOV with the voxlap models on and they will look all spaced out and hollow.

**Comment by Oxlot** [comment]
Betterspades aims to be as close as possible to the original beta version (voxlap), it already does visually so not more changes will be done in how the game looks like

**Comment by xtreme8000** [comment]
Fixed in https://github.com/xtreme8000/BetterSpades/commit/727db31cbb89eaf01f4359201a9c318a8482fe75
