### ISSUE TITLE
Game closes instantly

### ISSUE THREAD

**Issue by adterval** [xtreme8000/aof-opengl#114]
When i try to launch build n245 the game closes instantly, no errors, no crash log.

**Comment by xtreme8000** [comment]
Please provide some kind of error, either from the terminal, the `logs/` directory or e.g. a `gdb` stacktrace, otherwise this issue will be closed.

**Comment by adterval** [comment]
**It is fixed now, some PNG files were missing.**

i just dragged and replaced client.exe but i didn't know you added more PNG files to the game.
