### ISSUE TITLE
Server ?

### ISSUE THREAD

**Issue by molekel** [xtreme8000/aof-opengl#129]
Where can I find the sources for the server?

**Comment by JohnDowson** [comment]
https://github.com/piqueserver/piqueserver

**Comment by molekel** [comment]
just found it myself but its python *ew snakes*

**Comment by Rakete175** [comment]
Piqueserver is a mixture of Python and C. Some basic things (like physics) are made in C, the rest is written in Python.

If you dislike Python, check out https://github.com/SpadesX/SpadesX. It is a ground-up server implementation in C. Feel free to contribute there!

**Comment by xtreme8000** [comment]
I also have another server implementation written entirely in C in the works, however development is currently slow due to me not having enough spare time. It's main focus is on max multi-threaded performance.
Edit: I should probably just release it sometime so ppl can have a look at it.
