### ISSUE TITLE
Smooth fog with voxlap turned on 

### ISSUE THREAD

**Issue by ghost** [xtreme8000/aof-opengl#132]
![1630068090](https://user-images.githubusercontent.com/82431122/131129105-206f0a99-a1cc-4b65-89a3-2490aa6b6e9e.png)
![2021-08-27-204217_875x727_scrot](https://user-images.githubusercontent.com/82431122/131129025-a856c6dc-bb5a-4417-93f4-d7ba808b968c.png)
![1630068862](https://user-images.githubusercontent.com/82431122/131130586-a192fe5a-f97f-4824-851e-331cf992f350.png)
![2021-08-27-205443_871x727_scrot](https://user-images.githubusercontent.com/82431122/131130507-8ad02e34-17e4-4c1a-aa8e-81105589f48e.png)

**Comment by xtreme8000** [comment]
The `Smooth fog` option will be discontinued.

**Comment by ghost** [comment]
Isn't like discontinuing smooth fog too much?

**Comment by xtreme8000** [comment]
I want to merge rendering paths and have this planned for quite a while. `Smooth fog` is what the android version uses, but I want to try a new approach there, so that desktop and android use the same rendering style.

**Comment by ghost** [comment]
Ah i see, i was worried that you might actually remove the smooth fog altogether, do good work with it man 👍
