### ISSUE TITLE
The game isn't working for me.

### ISSUE THREAD

**Issue by GabrielSomething** [xtreme8000/aof-opengl#134]
Game disappears in the task manager, don't know what to do.
I hope this isn't something that WINDOWS 8.1 has to do.
![image](https://user-images.githubusercontent.com/49927160/132960851-dfe2d54d-7c3b-499b-ad02-70ef9a25d324.png)

**Comment by GabrielSomething** [comment]
oh yeah, also, there isn't anything in the damn log.

**Comment by xtreme8000** [comment]
> oh yeah, also, there isn't anything in the damn log

There really isn't any file in the `logs/` directory?
You can also try running the game from the terminal and see if there's any output.

**Comment by GabrielSomething** [comment]
A log exists in that dorectory, but it's just blank.
