### ISSUE TITLE
Servers are not fetching

### ISSUE THREAD

**Issue by OverwhelmingFire** [xtreme8000/aof-opengl#137]
For some reason some weeks ago servers stopped being fetched, so the launcher says "No servers" and shows me the empty list. Curiously, but sometimes it starts working again. Could you do something with that?
![Untitled](https://user-images.githubusercontent.com/34778977/144051478-baf9c700-3ad2-426a-9b13-79733f5ec8b7.png)

**Comment by DryByte** [comment]
If you access [Build and Shoot server list](http://services.buildandshoot.com/serverlist.json) in your browser, that loads without issues?

**Comment by OverwhelmingFire** [comment]
> If you access [Build and Shoot server list](http://services.buildandshoot.com/serverlist.json) in your browser, that loads without issues?

Yes, it opens perfectly well. A wanted also to add that I cannot enter on a server directly entering a link like "aos://168....." meanwhile in the vanilla build&shoot launcher the link works perfectly well and I join the server. Therefore it may have something to do with Betterspades thinking that I'm not connected to the net, that I'm offline
