### ISSUE TITLE
Cannot launch BetterSpades without Wayland (running on X11)

### ISSUE THREAD

**Issue by nonperforming** [xtreme8000/aof-opengl#143]
Built from latest commit at time (de8f77c)

OS: Manjaro x64
Kernel: 5.15.6-xanmod2-MANJARO

```
./client  
22:18:59 INFO  main.c:720: Game started!
22:18:59 FATAL main.c:671: Major error occured: [65544] Wayland: Failed to connect to display
```

Running KDE Plasma on Wayland fixes this issue. 
Is this intentional?

EDIT: Just noticed the typo. That also needs to be fixed as well, I think.

**Comment by xtreme8000** [comment]
maybe you installed e.g. the `glfw-wayland` package instead of `glfw-x11`?

**Comment by nonperforming** [comment]
This appears to be the problem. Removing `glfw-wayland` and installing `glfw-x11` fixes this problem. Closing issue
