### ISSUE TITLE
Mouse position has an offset with the displayed cursor.

### ISSUE THREAD

**Issue by Fran6nd** [xtreme8000/aof-opengl#145]
On my Mac m1, when I launch betterspades the UI is not showing up except the server list. Si I have to resize it one time to display it completely. But after I resize the window, the click position received by the game is always way to the left and down regarding the pointer's position displayed by the Mac. So to click on buttons it's really difficult and in some cases unpossible.

The version I run is built on my Mac from master directly.

Here, the screenshot shows the problem:

Looks like we are hovering the settings button but we are not.

<img width="703" alt="Screenshot 2022-02-10 at 18 07 32" src="https://user-images.githubusercontent.com/14808487/153460467-ec7aab12-6613-47a8-804f-0f1e97c4b9db.png">
.

**Comment by Fran6nd** [comment]
I successfully built and ran the demo of mini ui on my Mac m1. Seems not to be a bug in micro ui.

**Comment by Fran6nd** [comment]
As shown here, on startup I get the ui buggy. This is before I resize the window 1 time. Then all the UI appears. 
This is what I see at first.

<img width="804" alt="Screenshot 2022-02-10 at 20 16 11" src="https://user-images.githubusercontent.com/14808487/153480490-f1cf50cd-8f8e-477e-848b-fc7bc6c249db.png">

But again you can see the glitch: Not only on x axis but also on y.

 Seems that the offset increased as I move the mouse down. The y offset is 0 when I click on the settings button but is way bigger when I wanna click on a server in the list. Seems like a scaling problem?
 <img width="819" alt="Screenshot 2022-02-10 at 20 18 08" src="https://user-images.githubusercontent.com/14808487/153481348-2b1a5268-1932-4155-b71f-1015110bd4b1.png">

Edit: Before rescaling the window to display the full UI, I can click on a server and join it without any offset. But when I rescale the window to show the full UI, the offset problem appears.

**Comment by Fran6nd** [comment]
Here are infos I get on startup:

```
20:28:05 INFO  main.c:720: Game started!
20:28:05 INFO  main.c:731: Vendor: Apple
20:28:05 INFO  main.c:732: Renderer: Apple M1
20:28:05 INFO  main.c:733: Version: 2.1 Metal - 76.3
20:28:05 INFO  chunk.c:84: 1 cores enabled for chunk generation
20:28:05 INFO  font.c:116: font texsize: 128:256px [size 16.000000] type: 0
20:28:05 INFO  hud.c:2368: newest game version: v0.1.5
20:28:05 INFO  hud.c:2369: current game version: v0.1.5
```

**Comment by Fran6nd** [comment]
A workaround for now is to reduce the size of the news layout and to add only one server to the list. If I add more servers, the UI die...
Here is what I get directly when I run the client with this workaround: The UI showing up, no mouse offset BUT if I resize the window, the offset is back. And I need to see other servers :)
If I resize the window, everything shows up but I got the offset back...
<img width="790" alt="Screenshot 2022-02-10 at 21 49 33" src="https://user-images.githubusercontent.com/14808487/153494456-e9f89ab3-d876-4134-aa25-06d02fb7df1a.png">

**Comment by Fran6nd** [comment]
If found out that `mu_layout_next()` returns a wrong rect with a 2 times bigger position after the first resizing (using `reshape `) of the window. And the mouse coordinates received are ok.
What I do not understand is how the soft can draw properly rects but the click's rect seems bad.

**Comment by Fran6nd** [comment]
I found that the solution is applying a coef 2 to the mouse input sent to the app. That's what I did in my PR. Seems barbarian isn't it?

**Comment by Fran6nd** [comment]
One more point: even moving back from 100 commits didn't change anything about the offset problem and the UI bug before resizing the window. I really have no clue why at first the UI suck but offsets and rects seems good, resizing the window (smaller, bigger, fullscreen...) fix the UI and need now a coef 2 to be applied to the mouse position.

**Comment by yvt** [comment]
This problem looks like a symptom of a mix-up between logical and physical pixel coordinates. All iMac and MacBook models released in the last few years have high-resolution *built-in* displays which are configured as Hi-DPI *by default*.

**Comment by xtreme8000** [comment]
This is probably a GLFW3 issue, you could try using SDL2 instead.

**Comment by Fran6nd** [comment]
> This problem looks like a symptom of a mix-up between logical and physical pixel coordinates. All iMac and MacBook models released in the last few years have high-resolution _built-in_ displays which are configured as Hi-DPI _by default_.

Thanks for giving me these informations... I didn't know it. So the problem might be located into the graphic lib misunderstanding the screen resolution? (Getting 2 times less).

Because my fix is so ugly right now. I wonder if there is another way of fixing this... And so using `#ifndef __APPLE__` to apply the fix is wrong ?

**Comment by yvt** [comment]
> So the problem might be located into the graphic lib misunderstanding the screen resolution?

Or the app misunderstanding the position and size values used by the graphics library. Or the graphics library poorly documenting its interface.

[glfw 3.0 release note](https://www.glfw.org/docs/latest/news.html#news_30_hidpi) says:

> GLFW now supports high-DPI monitors on both Windows and macOS, giving windows full resolution framebuffers where other UI elements are scaled up. To achieve this, [glfwGetFramebufferSize](https://www.glfw.org/docs/latest/group__window.html#ga0e2637a4161afb283f5300c7f94785c9) and [glfwSetFramebufferSizeCallback](https://www.glfw.org/docs/latest/group__window.html#gab3fb7c3366577daef18c0023e2a8591f) have been added. These work with pixels, while the rest of the GLFW API works with screen coordinates. This is important as OpenGL uses pixels, not screen coordinates.

A possible "easy" fix is to disable the application-level Hi-DPI support (i.e., the state in which `logical coordinates != pixels`) altogether. Looking at glfw's documentation, setting [`GLFW_COCOA_RETINA_FRAMEBUFFER`](https://www.glfw.org/docs/latest/window_guide.html#GLFW_COCOA_RETINA_FRAMEBUFFER_hint) to `GLFW_FALSE` might just work. I'm not sure about other platforms.

> This is probably a GLFW3 issue, you could try using SDL2 instead.

This should work. SDL2 made a sensible choice of making Hi-DPI support opt-in and not breaking unprepared applications (including OpenSpades 0.1.x).

**Comment by Fran6nd** [comment]
> > So the problem might be located into the graphic lib misunderstanding the screen resolution?
> 
> Or the app misunderstanding the position and size values used by the graphics library. Or the graphics library poorly documenting its interface.
> 
> [glfw 3.0 release note](https://www.glfw.org/docs/latest/news.html#news_30_hidpi) says:
> 
> > GLFW now supports high-DPI monitors on both Windows and macOS, giving windows full resolution framebuffers where other UI elements are scaled up. To achieve this, [glfwGetFramebufferSize](https://www.glfw.org/docs/latest/group__window.html#ga0e2637a4161afb283f5300c7f94785c9) and [glfwSetFramebufferSizeCallback](https://www.glfw.org/docs/latest/group__window.html#gab3fb7c3366577daef18c0023e2a8591f) have been added. These work with pixels, while the rest of the GLFW API works with screen coordinates. This is important as OpenGL uses pixels, not screen coordinates.
> 
> A possible "easy" fix is to disable the application-level Hi-DPI support (i.e., the state in which `logical coordinates != pixels`) altogether. Looking at glfw's documentation, setting [`GLFW_COCOA_RETINA_FRAMEBUFFER`](https://www.glfw.org/docs/latest/window_guide.html#GLFW_COCOA_RETINA_FRAMEBUFFER_hint) to `GLFW_FALSE` might just work. I'm not sure about other platforms.
> 
> > This is probably a GLFW3 issue, you could try using SDL2 instead.
> 
> This should work. SDL2 made a sensible choice of making Hi-DPI support opt-in and not breaking unprepared applications (including OpenSpades 0.1.x).

Thanks for the reply. I tried it, adding `glfwWindowHint(GLFW_COCOA_RETINA_FRAMEBUFFER, GLFW_FALSE);` and it worked!
So I've updated my PR.

I am also trying a migration to DSL2 as it would be better. But I am kinda new to the relation between OpenGL and SDL2, GLFW... So it might taker some times. If I correctly understood, the idea would be to replace completely GLFW by SDL2?

**Comment by xtreme8000** [comment]
> I am also trying a migration to DSL2 as it would be better. But I am kinda new to the relation between OpenGL and SDL2, GLFW... So it might taker some times. If I correctly understood, the idea would be to replace completely GLFW by SDL2?

SDL2 support is already mostly implemented, you only need to enable the SDL2 switch in CMake, i.e.
```
cmake -DENABLE_SDL=ON -DENABLE_GLFW=OFF ..
```

**Comment by xtreme8000** [comment]
Can I close this?
