### ISSUE TITLE
cglm problem in the build

### ISSUE THREAD

**Issue by HunoEru** [xtreme8000/aof-opengl#149]
I am updating the BetterSpades package in the [AUR](https://aur.archlinux.org/packages/betterspades), so I was testing the build to pass this to PKGBUILD. Then I ran into this [error](https://dpaste.com/8YVBF9VNT).

After trying a few things, I was able to solve the problem just by changing the cglm version in CMakeLists.txt (nano BetterSpades-0.1.5/src/CMakeLists.txt) from 0.8.0 to 0.8.4 (latest according to cglm's github). So I was able to do the build and everything went fine. I am still trying to figure out how I can make this change in PKGBUILD but it would be nice to change the version to make it easier for everyone who wants to compile BS.

(I don't understand Github that much, so if by chance it is possible to change this by yourself as a contributor, I apologize)

**Comment by HunoEru** [comment]
I just saw that there has already been this cglm depedency change, but the source-code.tar.gz is still outdated. I hope this will be resolved soon.

**Comment by xtreme8000** [comment]
The AUR package is unofficial and I have no idea who created it. Please do not use it.

**Comment by HunoEru** [comment]
I am not using it, I am updating it. It was very outdated and the code had some errors, now I am the maintainer
