### ISSUE TITLE
OpenAL32.dll

### ISSUE THREAD

**Issue by HunoEru** [xtreme8000/aof-opengl#150]
When I run "sudo make install", I get this error:
`CMake Error at src/cmake_install.cmake:72 (file):
  file INSTALL cannot find
  "/home/huno/BetterSpades/build/BetterSpades/OpenAL32.dll": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)`

**Comment by xtreme8000** [comment]
The CMake install target is only meant for Windows.
