### ISSUE TITLE
Show raw orientation in 1st person spectator. 

### ISSUE THREAD

**Issue by VierEck** [xtreme8000/aof-opengl#151]
the biggest issue preventing server moderators of all players using this client more often is orientation interpolation in 1st person spectator. 
its misleading, u cant make out aimbot, inexperienced players sometimes even falsely get an expression of someone using esp. 

make it show raw orientation to eliminate these issues pls. ngl i would be playing on bs more often if it werent for this problem. 

idk about the code and technicality, but maybe alternatively just disable interpolation  for the player being spectated when in 1st person spectator.  
interpolation do be eyecandy some may like  so that way u have the benefit of still having interpolation but just not for the player u spectate in 1st person thus making the client also a good option for moderators.

**Comment by VierEck** [comment]
not sure whats so confusing. well then, tldr:

The spectator mode in betterspades is useless as a tool to identify cheaters ingame. 
Dont be surprised when most players who do would like to have a clear judgement wether someone is cheating or not, choose to go with other clients and drop betterspades.

**Comment by Rakete175** [comment]
Agree, interpolated orientations give the illusion of having a flawless network, however the price is that they make it more difficult to spectate for cheats. As you mention, the orientations of players do matter, especially when it's about recoil.

It looks to me like the interpolation is done here: https://github.com/xtreme8000/BetterSpades/blob/161a28af039ce2dec3cf270137d50cfe86f19adf/src/player.c#L276

**Comment by xtreme8000** [comment]
This is intended behavior, so I might add a switch to allow you to turn it off for the purpose of cheater spectating.
