### ISSUE TITLE
add support for raspberry pi

### ISSUE THREAD

**Issue by tigercoding56** [xtreme8000/aof-opengl#173]
as openspades does not compile on the raspberry pi ,
could you try to add support for it 
i am still testing if it will compile [50% done]

**Comment by tigercoding56** [comment]
nvmind it compiled :D

**Comment by xtreme8000** [comment]
BS works on any raspberry pi, even model 1B (I tested it myself years ago, needs OpenGL ES mode enabled in cmake config).
