### ISSUE TITLE
When in full screen mode the client doesn't restore properly after being minimized 

### ISSUE THREAD

**Issue by shywolf91** [xtreme8000/aof-opengl#21]

**Comment by xtreme8000** [comment]
What does this mean? To which state should it restore?

**Comment by shywolf91** [comment]
not sure if its just my computer (SP3, windows 10) but when I alt-tab out of the game to check something on my desktop and then restore the client it won't fill up the whole screen but only a small portion beginning at the left corner.

**Comment by oldmud0** [comment]
Heh, just like the GDI days.

**Comment by Edgamer63** [comment]
is that the resolution? xD

**Comment by xtreme8000** [comment]
This works as expected on my machine, brings me right back into fullscreen after "tabbing" back in.
