### ISSUE TITLE
Weapon disappears when looking straight down

### ISSUE THREAD

**Issue by NotAFile** [xtreme8000/aof-opengl#22]

**Comment by xtreme8000** [comment]
More information needed. I could not reproduce this.

**Comment by NotAFile** [comment]
I'll try. I don't remember the specific conditions though.

**Comment by NotAFile** [comment]
I can reproduce this just by joining a server and looking exactly down.

**Comment by xtreme8000** [comment]
confirmed, happend on linux for me.
