### ISSUE TITLE
Weapon does not move smoothly when turning

### ISSUE THREAD

**Issue by NotAFile** [xtreme8000/aof-opengl#23]
Instead, it glitches around happily

**Comment by xtreme8000** [comment]
Can you please check if 1d148aba60a7981f8c682c99647e58f6aea0ef67 resolved this? I think it is good enough atm.

**Comment by xtreme8000** [comment]
This is now finally fixed in 639a5d1dbcfb5e3cf90315eac20a66cfbaa415e0.
