### ISSUE TITLE
Please add support for Version Get and Version Send packets

### ISSUE THREAD

**Issue by feikname** [xtreme8000/aof-opengl#31]
Those are extensions to the 0.75 protocol supported by PySnip and piqueserver (perhaps even pyspades) that allow the server to query the client name and version and  a few other things, as specified [here](https://github.com/yvt/openspades/wiki/Network-Protocols#33-version-get-s2c).

While not very useful right now, except for statistical purposes, it can be used in the future to improve UX and for new features via feature flags while optionally remaining backwards compatible (e.g. an "all vs boss" server checking if a given client supports Entity packets as you proposed and otherwise kicking the player)

**Comment by MuffinTastic** [comment]
it already does have support for that, though. it uses character `B`. in fact, weeks ago I updated the aloha.pk servers to support that character in detectclient.py

**Comment by xtreme8000** [comment]
I think this issue is mostly about the `Enhanced variant` of the packet.

However I don't think I'll impl. the openspades packets for feature detection (they don't seem to be in use rn anyway) and rather work out a new protocol together with the folks at [pique](https://github.com/piqueserver/aosprotocol).

**Comment by feikname** [comment]
> it already does have support for that, though. it uses character B. in fact, weeks ago I updated the aloha.pk servers to support that character in detectclient.py

My tests were made using pique's `/client` command, which outputs "Unknown" with BetterSpades currently, so I didn't realize this was already implemented. Oops :sweat_smile: 

Should this issue be closed?
