### ISSUE TITLE
There is no way to enter custom server addresses anymore

### ISSUE THREAD

**Issue by feikname** [xtreme8000/aof-opengl#34]
Previously, it was possible to do `./client -<address>` to connect to private servers (unlisted, localhost, LAN party, etc), but now this is no longer possible.

I suggest re-adding both the old method and a new user input textbox in the server browser.

**Comment by feikname** [comment]
Partially solved by #35.

**Comment by xtreme8000** [comment]
Solved by 6af0deae40ff5ce607adff41a7dd1ebba46e3b9a
