### ISSUE TITLE
Player velocity is not added to thrown grenade velocity

### ISSUE THREAD

**Issue by MuffinTastic** [xtreme8000/aof-opengl#36]
in the AoS classic and OpenSpades clients, grenade velocity is player orientation + player velocity.

for instance, this line (i think?)
https://github.com/xtreme8000/BetterSpades/blob/340f366ed2a8d807f3dd0400a0a7bb2a5d9af028/src/hud.c#L893
should be something like
`g.vx = (g.fuse_length==0.0F)?0.0F:(players[local_player_id].orientation.x+players[local_player_id].physics.velocity.x); `

**Comment by xtreme8000** [comment]
I really wanted to merge your PR, but I did not know how to resolve those conflicts. I will give credit after adding this myself. (Code location is correct)
Also I think it's probably needed to add the shooters velocity to the tracers aswell.
