### ISSUE TITLE
Weapon Packets Bug

### ISSUE THREAD

**Issue by Edgamer63** [xtreme8000/aof-opengl#37]
Well i see a really important Bug in the Last Release, that is a Weapon-Packet Error, or imprecisions.

[https://youtu.be/Av72lmX5xBc](https://youtu.be/Av72lmX5xBc)

well, this happens after I tried to change my weapon,  so it does, but... this is the bug that happens, and  i'm not really sure why, but i notice it because it will improve a bit more the game performance.

It's really strange, it suddenly change from  SMG, to the last weapon , that in this case is RIFLE.

Well, Keep Going on with this amazing work :D , i will support you as i can.

**Comment by xtreme8000** [comment]
I had this happen before (maybe twice), not sure what caused it.

**Comment by natan5388** [comment]
will you host a server log the game and compares the log of the server with the game you would get to find the possible failure?
