### ISSUE TITLE
Fonts not scaled properly

### ISSUE THREAD

**Issue by oldmud0** [xtreme8000/aof-opengl#40]
Even with default resolution, the larger Fixedsys font does not seem to be rendering at correct scale.

![image](https://user-images.githubusercontent.com/5247009/36494863-fb4bf6c8-16f8-11e8-9b08-e3bd39b82c2f.png)

When the window is set to fullscreen, the same scaling problem occurs for the small chat font as well.

**Comment by xtreme8000** [comment]
**Update:** I played around with ttf font rendering in the last months.
While this gives good results for fixedsys; this won't work for smallfnt, as it is a bitmap only font.

**Comment by xtreme8000** [comment]
This is mostly fixed with de0365b2d62776419eda86adb15d5ab53fbc2f96
