### ISSUE TITLE
Technical Support help (load and save .vxl maps):

### ISSUE THREAD

**Issue by Edgamer63** [xtreme8000/aof-opengl#45]
Hello, it's a technical question. With this, i want to know how the vxl engine that uses betterspades to load and save maps work... because i want to load ".vxl" maps in my project called Battlexel (https://github.com/Edgamer63/Battlexel), to load  ".vxl" maps into map editor (my project)... I think i know that AoS (Original) & BetterSpades uses maps dimensions of [x,y,z]: 512,512,64...

What i want to know from a simple map (vxl), is the count of total blocks in map, the position of all ones [x,y,z], and the color (24 bit (RGB)).

And how to save to vxl map.

I have an example of how my map engine save maps more easily to understand and with a very smaller size.
_______________________________________________________________________________________________________________
for example, the block id here is 70:

The high, in this case, is the "Z" position.

color_x and color_y are based on colors of block palette (i will implement RGB colors Support anyways xD):

![](https://github.com/Edgamer63/Battlexel/blob/master/Battlexel%E2%84%A2%20Source/sprites/images/sprite9_0.png?raw=true)  X
Y

vxl_70_high="0"
vxl_70_color_y="2"
vxl_70_color_x="4"
vxl_70_y="6"
vxl_70_x="12"

# in this case the block have a high of 0 (floor), position x,y : (12,6) and color red .

Well, this applies to all items in a map... because it can be used for intels locations, base locations, even choppers, tanks and mg xD.

For example:

Base_1_x = "50"
Base_1_y = "50"
Base_1_high = "3"
Base_1_team = "2"

# Base pos is [x,y] = 50,50, with high of 3 blocks and team is "2" (Green).

_______________________________________________________________________________________________________________

Thats it, could you help me? :3 , i still being newbie in programming hahah ... but all i want to do, is to expand the game more... because i think my project would support very big huge maps created by community.

**Comment by xtreme8000** [comment]
The code and information on [this page](https://silverspaceship.com/aosmap/aos_file_format.html) should cover everything you want to know.
Keep in mind that the vxl format is more like a stream of an 2D-array that contains vertical columns of blocks.
