### ISSUE TITLE
Need help on buliding

### ISSUE THREAD

**Issue by kmsiapps** [xtreme8000/aof-opengl#5]
I got an error when compiling. ( http://pastebin.com/PAc5NFbZ )
Here is what I put on each directory - ( http://pastebin.com/jd6uxpC6 )
I'm quite noob on building stuff, so it might be very stupid mistake..

Anyway, thanks for this brilliant new client :)

**Comment by xtreme8000** [comment]
Okay so:
* rename `dr_wav.h` to `dr_wav.c`
* rename `libdeflate.lib` to either `deflate.lib` *or* `libdeflate.a`
* delete all LodePNG stuff except for `lodepng.c` and `lodepng.h` (this includes `src/pngdetail.cpp`)
* delete `glfw3.dll` and `glfw3dll.lib` from `lib/` those arent needed either

I'm not exactly sure what causes your GLFW3 and enet linking errors, but are you sure they are compatible to gcc? The missing functions `__GSHandlerCheck` and `__security_check_cookie` indicate these libraries were built with MSVC.
For GLFW3, download [this](https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN32.zip), you will need `lib-mingw/libglfw3.a` from the zip.

**Comment by xtreme8000** [comment]
Something I forgot regarding `dr_wav.c` is you will have to uncomment Line 9 , which will define `DR_WAV_IMPLEMENTATION`

**Comment by kmsiapps** [comment]
Thank you for your kind response. Still I got some errors yet.

> make
Scanning dependencies of target client
[  5%] Building C object CMakeFiles/client.dir/src/dr_wav.c.obj
make[2]: *** No rule to make target '../libs/glfw3.lib', needed by 'bin/client.exe'.  Stop.
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/client.dir/all' failed
make[1]: *** [CMakeFiles/client.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
make: *** [all] Error 2


This is what I put on my /libs directory:

> C:\Users\User\Downloads\BetterSpades-standalone\libs`

-a----     2017-10-28   오후 1:48             70 .gitignore
-a----     2015-04-30  오후 10:43          51152 enet.lib
-a----     2017-07-29   오후 2:46          42436 libdeflate.a
-a----     2016-08-18   오후 2:04         139032 libglfw3.a
-a----     2017-09-24  오후 10:49         118460 OpenAL32.lib

**Comment by kmsiapps** [comment]
Thank you for your kind response. 

Existing errors had been fixed after replacing files, cleaning /build and rebuilding.
But I got another error: https://pastebin.com/c5y423du

I used `lib-mingw/libglfw3.a` as you suggested.
I'm using `mingw-w64` on `Windows 10 x64`.

**Comment by xtreme8000** [comment]
Well for x64 you obv need the 64 bit library of [glfw](https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.bin.WIN64.zip) (`lib-mingw-w64/libglfw3.a` in the zip).

Your enet build is still not accepted by gcc, maybe rebuild that one with mingw-w64?

> You should be able to compile it with the `msys` (+`autotools`) environment on windows, which you can download as a package from the mingw-updater. (for me its installed on path `C:\MinGW\msys\1.0\msys.bat`)

**EDIT: I just found out enet can also be build with cmake, which is prob easier. It will work with the same command like on this project**

**Comment by kmsiapps** [comment]
I finally succeeded in compiling. Thanks.
Redownloaded enet, glfw and libdeflate, and It worked like a charm :)

Attaching sources just in case someone needed it.
[BetterSpades-standalone.zip](https://github.com/xtreme8000/BetterSpades/files/1463467/BetterSpades-standalone.zip)

**Comment by Edgamer63** [comment]
ehm... now, how do I play? I tried with F2, so not much happens, help me xD

**Comment by xtreme8000** [comment]
Keyboard commands:
* **F1-F4**: change camera mode *(F1: top down view, F2: first person, F3: free camera, F4: third person)*
* **V**: be careful, this one teleports you to the center of the map (only for testing, might get you banned)
* **8**: will join the server defined in `main.c` at `Line 1071`
* **9**: will join the best team, *Green*

Note that this can change any time in the future, and is only temporary.
