### ISSUE TITLE
How do I play it (after compiled)

### ISSUE THREAD

**Issue by Edgamer63** [xtreme8000/aof-opengl#6]
Uhm, I have a question. It's simple, how do I play it after compiled?
I press F2 and the game shows like a normal aos, without any block and with an aqua background color, and a super-bugged SMG xD.

**Comment by xtreme8000** [comment]
> Copied from #5

Keyboard commands:
* **F1-F4**: change camera mode *(F1: top down view, F2: first person, F3: free camera, F4: third person)*
* **V**: be careful, this one teleports you to the center of the map (only for testing, might get you banned)
* **8**: will join the server defined in `main.c` at `Line 1071`
* **9**: will join the best team, *Green*

Note that this can change any time in the future, and is only temporary.
