### ISSUE TITLE
cannot compile on rpi 3B raspbian 

### ISSUE THREAD

**Issue by ghost** [xtreme8000/aof-opengl#69]
UPDATE: i added -ldeflate to link.txt in build/CMakeFiles/client.dir/link.txt and now deflate issues is gone but it still fails at drwav:

CMakeFiles/client.dir/src/sound.c.o: In function `sound_load':
sound.c:(.text+0x908): undefined reference to `drwav_open_and_read_file_s16'
collect2: error: ld returned 1 exit status

line 9 in dr_wav.h is not the #define statement and the file also has deprecation warning in it
(drwav_open_and_read_s16() should be drwav_open_and_read_pcm_frames_s16() according to it)

**Comment by feikname** [comment]
I had a similar issue when compiling BetterSpades once, can't remember how I fixed it. (~~I actually had a .patch specifically for that issue~~ nevermind, it was for GLFW linking issues)

I think it had something to do with the order of CMake linking or with the order of the `#include`s.

**Comment by ghost** [comment]
dr_wav.c doesnt even seem to be compiled to an object at all

**Comment by feikname** [comment]
Regarding the line 9, the readme instructions are indeed wrong. Just define it right before the dr wav import in `sound.c`

**Comment by xtreme8000** [comment]
There was a recent change to the API of `dr_wav`, please try an older version of that same library.

**Comment by feikname** [comment]
@xtreme8000 Wouldn't it be better to include `#define DR_WAV_IMPLEMENTATION` in BetterSpades's  code so people don't have to edit files?

**Comment by feikname** [comment]
https://github.com/mackron/dr_libs/blob/3d33f449264da333484076729007284ea70afe70/dr_wav.h
^ This version should be fine

**Comment by ghost** [comment]
i redid cmake and added target_link_libraries(client dl) and target_link_libraries(client X11) and it worked

**Comment by ghost** [comment]
closed for now
