### ISSUE TITLE
Walking sound still played while sneaking

### ISSUE THREAD

**Issue by 1AmYF** [xtreme8000/aof-opengl#73]
When you walk and either press v or scope while not changing your movement otherwise, your walking sound is still played on for about 4 seconds or so. It works correct though if you directly crouch or change your direction.

**Comment by xtreme8000** [comment]
The client determines whether foot steps should be played based on a player's walking speed. When walking normally and then sneaking you're actually slowing down smoothly and not directly which results in the slow "detection".
