### ISSUE TITLE
Display team color in FPV

### ISSUE THREAD

**Issue by NotAFile** [xtreme8000/aof-opengl#76]
It is hard to tell what team color you are on, as your team color is not displayed in FPV.

**Comment by xtreme8000** [comment]
Would it be enough to show the player's map quadrant below the minimap in team color?

**Comment by NotAFile** [comment]
might be hard to read depending on the team color. But map quadrant would be nice in general.

**Comment by NotAFile** [comment]
actually, sector is a more accurate term, since quadrant implies that there's only 4 of them.
