### ISSUE TITLE
After you press T/Y to open chat, the first letter that you type in will always disappear

### ISSUE THREAD

**Issue by minhla** [xtreme8000/aof-opengl#77]
Just like what the title says, I found this bug while chatting.

**Comment by xtreme8000** [comment]
That has been fixed in https://github.com/xtreme8000/BetterSpades/commit/126fbf1dcdb3aeb282c40883aaac922b75c4c6a5 shortly after the release of v0.1.3
(duplicate of https://github.com/xtreme8000/BetterSpades/issues/58)
