### ISSUE TITLE
Use raw mouse input

### ISSUE THREAD

**Issue by teodor6140** [xtreme8000/aof-opengl#86]
The mouse moves faster up-left than down-right by roughly a pixel, this makes aiming hard. Might be caused by getting the wrong mouse offset on window?
X11/Linux

**Comment by NotAFile** [comment]
I've had similar problems with the aim being strange, but I could never pinpoint exactly what it was.

**Comment by teodor6140** [comment]
It works fine when i use SDL lel, but now half the keys don't work :(((

**Comment by teodor6140** [comment]
Found the problem
GLFW doesn't use raw input by default.
https://github.com/otzade/BetterSpades/commit/5526949fd90bf8751b30f83589e3e2cf9d196e55

**Comment by NotAFile** [comment]
can you make a PR for that?

**Comment by teodor6140** [comment]
https://github.com/xtreme8000/BetterSpades/pull/87
