### ISSUE TITLE
macOS: Search paths are not set properly

### ISSUE THREAD

**Issue by yvt** [xtreme8000/aof-opengl#88]
`README.md` instructs to install external dependencies using one of these package managers:

> The same instructions for Linux work on macOS aside from some minor differences. First, use Homebrew or MacPorts to grab dependencies:

They install header/library files to non-system locations such as `/usr/local` and `/opt/local`, which are not included in the default search paths, causing compilation errors such as:

```
In file included from /Users/tcpp/Programs/Games/BetterSpades/src/aabb.c:20:
/Users/Nobody/BetterSpades/src/common.h:36:11: fatal error: 'enet/enet.h' file not found
        #include <enet/enet.h>
                 ^~~~~~~~~~~~~
1 error generated.
```

`CMakeLists.txt` should contain appropriate directives (e.g., `find_package`, `include_directories`) to configure the search paths for those external libraries.

**Comment by NotAFile** [comment]
I think this is #56 which hasn't been merged so far.
