### ISSUE TITLE
I suggest 2 things :3

### ISSUE THREAD

**Issue by Edgamer63** [xtreme8000/aof-opengl#9]
https://github.com/xtreme8000/BetterSpades/blob/2b56d0ff860061affa9d2ae25f19ce081bbd3b51/src/main.c#L1519

Hello my friend! :D  ...

* I suggest to write the "reload" text, more upper, because the weapon aim, like "smg.png" are drawn on the text, and normal player will not be allowed to see the text of "Reload". In this example, you could see only "Eloa", and not the whole word "Reload".

<img src="https://user-images.githubusercontent.com/16976638/34013470-6bc02c78-e0f6-11e7-85c0-4f73d41454d5.png" width="60%">

* And, I don't know where the keyboard checking is, but... I recommend to delete the first char in a lapse after the key checking of the chat message, because if you press the "T"(Global Message by default), shows the message line, but with an unwanted letter "t" on first character. Also on the Team message it is the same case, but with letter "y". That's why I recommend to delete the first character.

<img src="https://user-images.githubusercontent.com/16976638/34015139-526b9c2a-e0fc-11e7-9db3-b62d155a9172.png" width="60%">

**Comment by chikin-eetar** [comment]
![](https://i.imgur.com/RtUd1su.png)

**Comment by Edgamer63** [comment]
hahahahah! nice joke xDDDD

**Comment by xtreme8000** [comment]
I will reorder drawing of the HUD to move the "Reload" message to the front. Your second issue is already fixed in next commit.

Also just for clarification, that text is actually drawn here:
https://github.com/xtreme8000/BetterSpades/blob/2b56d0ff860061affa9d2ae25f19ce081bbd3b51/src/main.c#L709
