### ISSUE TITLE
Broken terrain display

### ISSUE THREAD

**Issue by pachuco** [xtreme8000/aof-opengl#95]
Display of level geometry is severely broken, everything transparent. tested with latest release and nightly, as of this writing.

![not_so_betterspades](https://user-images.githubusercontent.com/1591054/68983416-895a0380-0813-11ea-8afa-887ab500b46b.png)

**Comment by pachuco** [comment]
Oh, almost forgot, specs:
OS: XP SP3 x86
GPU: Nvidia Quadro 600

**Comment by pachuco** [comment]
Ok, forgot settings.
This occurs in windowed mode. Display works perfectly in fullscreen.
Smooth Fog fixes display of terrain and works with both windowed and fullscreen.
Enabling Multisampling of any kind brings back terrain defects regardless if Smooth Fog is enabled.

Force Displaylist makes all terrain invisible in both modes.

**Comment by 1AmYF** [comment]
This happens when your face is partly (not entirely) covered in blocks. I assume you either glitched into blocks or other players have built upon you. I could reproduce it both in windowed and fullscreen.

**Comment by pachuco** [comment]
I see this in clear outdoors(I am able to move, as well).

Edit: I was wrong when I said Fullscreen with no Smooth Fog does not break terrain display.
It will eventually break it when there is enough lag in rendering.

This lag happens in certain places of certain maps more then others, but I am not sure what to tie it, exactly. The mentioned lag does not happen in original AoS, which runs smooth.

As example of a lag instance and display break instance:
1. I am in certain indoor Arena map(forgot which).
2. game is laggy while waiting in pen.
3. the door breaks, allowing contestants inside.
4. as soon as door breaks, terrain display has broken and game is smooth.

**Comment by pachuco** [comment]
Another strange aspect of this lag behaviour is that shooting into block(say, with shotgun) releases stress and makes game run smoother for very short while. Facing in other direction tends to return the lag.
