### ISSUE TITLE
BetterSpades console can't be closed

### ISSUE THREAD

**Issue by adterval** [xtreme8000/aof-opengl#97]
I had this problem some time ago, I already sent it on #bug-reports but I just want to share it here too.
![unknown](https://user-images.githubusercontent.com/52900575/69895499-9c320500-12f6-11ea-8966-1a2b2068212c.png)

**Comment by pielover88888** [comment]
in a run prompt, run `taskkill /F /IM client.exe` and it'll definitely go away.
